require "callback"
require "./optarg/util/*"
require "./optarg/*"
require "./optarg/value_types/*"
require "./optarg/definition_mixins/*"
require "./optarg/definitions/*"
require "./optarg/bash_completion/*"
require "./optarg/bash_completion/functions/*"
